modLoader = "javafml"
loaderVersion = "[47,)"
license = "Terrarium License"
issueTrackerURL = "https://github.com/terrarium-earth/ad-astra/issues"

[[mods]]
modId = "adastra"
version = "${file.jarVersion}"
displayName = "Ad Astra"
displayURL = "https://modrinth.com/mod/ad-astra"
logoFile = "icon.png"
authors = "Alex Nijjar"
credits = "CodexAdrian, Facu, Fizz, ThatGravyBoat"
description = "Live long and prosper, Ad Astra!"

[[dependencies.adastra]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adastra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adastra]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adastra]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adastra]]
modId = "botarium"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "NONE"
side = "BOTH"