modLoader = "javafml"
loaderVersion = "[47,)"
license = "Terrarium License"
issueTrackerURL = "https://github.com/terrarium-earth/ad-astra/issues"

[[mods]]
modId = "ad_astra"
version = "${version}"
displayName = "Ad Astra"
displayURL = "https://modrinth.com/mod/ad-astra"
logoFile = "icon.png"
authors = "Alex Nijjar"
credits = "CodexAdrian, Facu, Fizz, MsRandom, ThatGravyBoat"
description = "Live long and prosper, Ad Astra!"

[[dependencies.ad_astra]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "botarium"
mandatory = true
versionRange = "[2.3.0,)"
ordering = "NONE"
side = "BOTH"
