modLoader="javafml"
loaderVersion="[39,)"
license="Not specified"

[[mods]]
modId="astrocraft"
version="5.7"
displayName="AstroCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/astrocraft"
logoFile="logo.png"
authors="MrScautHD"
description='''
Fly to Other Planets and Beyond!
'''

[[dependencies.astrocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.astrocraft]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,]"
    ordering="NONE"
    side="BOTH"